### ISSUE TITLE
Categories with hyphen in the name [patch]

### ISSUE THREAD

**Issue by rcaimi** [HardySimpson/zlog#102]
Is there a reason that categories with hyphen are not found by zlog?

I registered a "link-status" category, but it fails, the same does not happen to "link_status"...

My conf file:
[global]
strict init = false
buffer min = 1024
buffer max = 2MB

[formats]
debug = "%n%d(%F %T).%us [%c] %m"

[rules]
link-status.* "/dev/console"; debug
link_status.* "/dev/console"; debug

Zlog_PROFILE_DEBUG:

07-23 01:19:57 DEBUG (3576:zlog.c:119)  ------zlog_init start------
07-23 01:19:57 DEBUG (3576:zlog.c:120) ------compile time[May  5 2017 16:15:46], version[1.2.12]------
07-23 01:19:57 DEBUG (3576:spec.c:41) ----spec[0x10027310][%n][|0][,0,0][]----
07-23 01:19:57 DEBUG (3576:spec.c:41) ----spec[0x10029748][%d(%F %T)][%F %T|0][,0,0][]----
07-23 01:19:57 DEBUG (3576:spec.c:41) ----spec[0x1002bb80][.][|0][,0,0][]----
07-23 01:19:57 DEBUG (3576:spec.c:41) ----spec[0x1002dfb8][%us][|0][,0,0][]----
07-23 01:19:57 DEBUG (3576:spec.c:41) ----spec[0x100303f0][ [][|0][,0,0][]----
07-23 01:19:57 DEBUG (3576:spec.c:41) ----spec[0x10032828][%c][|0][,0,0][]----
07-23 01:19:57 DEBUG (3576:spec.c:41) ----spec[0x10034c60][] ][|0][,0,0][]----
07-23 01:19:57 DEBUG (3576:spec.c:41) ----spec[0x10037098][%m][|0][,0,0][]----
07-23 01:19:57 DEBUG (3576:format.c:29) ---format[0x10025300][debug = %n%d(%F %T).%us [%c] %m(0x1001e0e8)]---
07-23 01:19:57 DEBUG (3576:spec.c:41) ----spec[0x1003b928][%D][%F %T|1][,0,0][]----
07-23 01:19:57 DEBUG (3576:spec.c:41) ----spec[0x1003dd60][ ][|0][,0,0][]----
07-23 01:19:57 DEBUG (3576:spec.c:41) ----spec[0x10040198][%V][|0][,0,0][]----
07-23 01:19:57 DEBUG (3576:spec.c:41) ----spec[0x100425d0][ [][|0][,0,0][]----
07-23 01:19:57 DEBUG (3576:spec.c:41) ----spec[0x10044a08][%p][|0][,0,0][]----
07-23 01:19:57 DEBUG (3576:spec.c:41) ----spec[0x10046e40][:][|0][,0,0][]----
07-23 01:19:57 DEBUG (3576:spec.c:41) ----spec[0x10049278][%F][|0][,0,0][]----
07-23 01:19:57 DEBUG (3576:spec.c:41) ----spec[0x1004b6b0][:][|0][,0,0][]----
07-23 01:19:57 DEBUG (3576:spec.c:41) ----spec[0x1004dae8][%L][|0][,0,0][]----
07-23 01:19:57 DEBUG (3576:spec.c:41) ----spec[0x1004ff20][] ][|0][,0,0][]----
07-23 01:19:57 DEBUG (3576:spec.c:41) ----spec[0x10052358][%m][|0][,0,0][]----
07-23 01:19:57 DEBUG (3576:spec.c:41) ----spec[0x10054790][%n][|0][,0,0][]----
07-23 01:19:57 DEBUG (3576:format.c:29) ---format[0x10039918][default = %D %V [%p:%F:%L] %m%n(0x1001d9a0)]---
07-23 01:19:57 DEBUG (3576:rule.c:966) zlog_rule_del[0x10056bc8]
07-23 01:19:57 DEBUG (3576:conf.c:45) -conf[0x1001e1c8]-
07-23 01:19:57 DEBUG (3576:conf.c:46) --global--
07-23 01:19:57 DEBUG (3576:conf.c:47) ---file[/etc/debug.conf],mtime[2015-07-23 01:19:07]---
07-23 01:19:57 DEBUG (3576:conf.c:48) ---strict init[0]---
07-23 01:19:57 DEBUG (3576:conf.c:49) ---buffer min[1024]---
07-23 01:19:57 DEBUG (3576:conf.c:50) ---buffer max[2097152]---
07-23 01:19:57 DEBUG (3576:conf.c:52) ---default_format---
07-23 01:19:57 DEBUG (3576:format.c:29) ---format[0x10039918][default = %D %V [%p:%F:%L] %m%n(0x1001d9a0)]---
07-23 01:19:57 DEBUG (3576:conf.c:55) ---file perms[0600]---
07-23 01:19:57 DEBUG (3576:conf.c:56) ---reload conf period[0]---
07-23 01:19:57 DEBUG (3576:conf.c:57) ---fsync period[0]---
07-23 01:19:57 DEBUG (3576:conf.c:59) ---rotate lock file[/etc/debug.conf]---
07-23 01:19:57 DEBUG (3576:rotater.c:50) --rotater[0x100394d0][0x100394d0,/etc/debug.conf,5][(null),(null),,0,0,0,0,0]--
07-23 01:19:57 DEBUG (3576:level_list.c:26) --level_list[0x1001d808]--
07-23 01:19:57 DEBUG (3576:level.c:26) ---level[0x10020620][0,*,*,1,6]---
07-23 01:19:57 DEBUG (3576:level.c:26) ---level[0x10020e38][20,DEBUG,debug,5,7]---
07-23 01:19:57 DEBUG (3576:level.c:26) ---level[0x10021650][40,INFO,info,4,6]---
07-23 01:19:57 DEBUG (3576:level.c:26) ---level[0x10021e68][60,NOTICE,notice,6,5]---
07-23 01:19:57 DEBUG (3576:level.c:26) ---level[0x10022680][80,WARN,warn,4,4]---
07-23 01:19:57 DEBUG (3576:level.c:26) ---level[0x10022e98][100,ERROR,error,5,3]---
07-23 01:19:57 DEBUG (3576:level.c:26) ---level[0x100236b0][120,FATAL,fatal,5,1]---
07-23 01:19:57 DEBUG (3576:level.c:26) ---level[0x10023ec8][254,UNKNOWN,unknown,7,3]---
07-23 01:19:57 DEBUG (3576:level.c:26) ---level[0x10024ae8][255,!,!,1,6]---
07-23 01:19:57 DEBUG (3576:conf.c:65) --format list[0x1001d838]--
07-23 01:19:57 DEBUG (3576:format.c:29) ---format[0x10025300][debug = %n%d(%F %T).%us [%c] %m(0x1001e0e8)]---
07-23 01:19:57 DEBUG (3576:conf.c:72) --rule_list[0x1001e0d0]--
07-23 01:19:57 DEBUG (3576:rule.c:65) ---rule:[0x10056bc8][link_status*0]-[384,0][/dev/console,(nil),6:0*0~][0][0][::(nil)];[0x100253
00]---
07-23 01:19:57 DEBUG (3576:category_table.c:22) -category_table[0x1001d9b8]-
07-23 01:19:57 DEBUG (3576:record_table.c:22) -record_table[0x1001dfe0]-
07-23 01:19:57 DEBUG (3576:zlog.c:142) ------zlog_init success end------
07-23 01:19:57 DEBUG (3576:zlog.c:335) ------zlog_get_category[link_status] start------
07-23 01:19:57 DEBUG (3576:category.c:26) --category[0x1001d000][link_status][0x1001c7d8]--
07-23 01:19:57 DEBUG (3576:rule.c:65) ---rule:[0x10056bc8][link_status*0]-[384,0][/dev/console,(nil),6:0*0~][0][0][::(nil)];[0x100253
00]---
07-23 01:19:57 DEBUG (3576:zlog.c:357) ------zlog_get_category[link_status] success, end------ 
07-23 01:19:57 DEBUG (3576:zlog.c:335) ------zlog_get_category[link-status] start------
07-23 01:19:57 DEBUG (3576:category.c:103) category[link-status], no match rules & no wastebin_rule
07-23 01:19:57 DEBUG (3576:category.c:26) --category[0x10059d78][link-status][0x1001c890]--
07-23 01:19:57 DEBUG (3576:zlog.c:357) ------zlog_get_category[link-status] success, end------

Is there a way to make "link-status" a valid category?

Regards

**Comment by rcaimi** [comment]
Hi...

I think the patch below fixes my problem!

From 32f7b040f4ac428a7d1cba352f58810a76b30c81 Mon Sep 17 00:00:00 2001
From: caimi <caimi@datacom.ind.br>
Date: Thu, 18 May 2017 08:36:21 -0300
Subject: [PATCH] Adds hyphen to valid rule name

Signed-off-by: caimi <caimi@datacom.ind.br>
---
 src/rule.c | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/src/rule.c b/src/rule.c
index 97cbbff..8526a9d 100644
--- a/src/rule.c
+++ b/src/rule.c
@@ -638,8 +638,8 @@ zlog_rule_t *zlog_rule_new(char *line,
 
        /* check and set category */
        for (p = category; *p != '\0'; p++) {
-               if ((!isalnum(*p)) && (*p != '_') && (*p != '*') && (*p != '!')) {
-                       zc_error("category name[%s] character is not in [a-Z][0-9][_!*]",
+               if ((!isalnum(*p)) && (*p != '_') && (*p != '-') && (*p != '*') && (*p != '!')) {
+                       zc_error("category name[%s] character is not in [a-Z][0-9][_!*-]",
                                 category);
                        goto err;
                }
-- 
2.7.4

Is it possible to evaluate if it can go upstream, and if it can possibly cause any trouble ?

Regards

Rodrigo

**Comment by henriquemarks** [comment]
Integrated In HEAD, waiting for Release now
