### ISSUE TITLE
有时候打时间戳， 有时候不打

### ISSUE THREAD

**Issue by zylthinking** [HardySimpson/zlog#111]
[formats]
simple = "%d %m"
[rules]
log.DEBUG "./zyl.log", 10MB * 3 ~ "zyl.log.#r"; simple

日志文件部分如下：
2017-11-03 11:31:36 st0124@test.com life extends to 2090135
2017-11-03 11:31:37 st0064@test.com life extends to 2090170
2017-11-03 11:31:37 st0005@test.com life extends to 2090178
create AQMkADQxZGE1ZTkzLWM1NDgtNGNlMy04ZTU0LThlMDM2NTAwAGIwYjAARgAAA6Lcybw064pHuFoJhNZA4kQHAHi0JzZm1tBAoyawYfqO0dAAAAIBDQAAAHi0JzZm1tBAoyawYfqO0dAAAAICLAAAAA== failed 404
create AQMkADQxZGE1ZTkzLWM1NDgtNGNlMy04ZTU0LThlMDM2NTAwAGIwYjAARgAAA6Lcybw064pHuFoJhNZA4kQHAHi0JzZm1tBAoyawYfqO0dAAAAIBDQAAAHi0JzZm1tBAoyawYfqO0dAAAAICKwAAAA== failed 404
create AQMkADQxZGE1ZTkzLWM1NDgtNGNlMy04ZTU0LThlMDM2NTAwAGIwYjAARgAAA6Lcybw064pHuFoJhNZA4kQHAHi0JzZm1tBAoyawYfqO0dAAAAIBDQAAAHi0JzZm1tBAoyawYfqO0dAAAAICKgAAAA== failed 404
create AQMkADQxZGE1ZTkzLWM1NDgtNGNlMy04ZTU0LThlMDM2NTAwAGIwYjAARgAAA6Lcybw064pHuFoJhNZA4kQHAHi0JzZm1tBAoyawYfqO0dAAAAIBDQAAAHi0JzZm1tBAoyawYfqO0dAAAAICKQAAAA== failed 404
create AQMkADQxZGE1ZTkzLWM1NDgtNGNlMy04ZTU0LThlMDM2NTAwAGIwYjAARgAAA6Lcybw064pHuFoJhNZA4kQHAHi0JzZm1tBAoyawYfqO0dAAAAIBDQAAAHi0JzZm1tBAoyawYfqO0dAAAAICKAAAAA== failed 404
2017-11-03 11:31:37 st0031@test.com life extends to 2090212

**Comment by HardySimpson** [comment]
把那行规则注释了呢，这些日志是否还会再打

**Comment by zylthinking** [comment]
应该是其他原因， 当时开了两个程序， 一个是修改配置文件加上时间戳前启动的
