### ISSUE TITLE
请问，程序运行过程中多次调用zlog_get_category会不会有问题？

### ISSUE THREAD

**Issue by IotCoder-LangZhe** [HardySimpson/zlog#113]
目前项目要求：实现多等级日志打印；各个等级日志路径不同，日志等级能够动态设定。原本设想使用自定义等级，但是低等级的自定义level和高等级的自定义level会把高等级的msg都打印出来。所以想借助category中的“_”下级分类做日志等级，这样等级改变运行过程中可能会调用zlog_get_category()这样安全吗？

**Comment by HardySimpson** [comment]
可以随便调用，但不建议这么做，在配置里面用 = 操作符就可以只输出一个等级了

**Comment by IotCoder-LangZhe** [comment]
你好，我的版本是1.2.7 使用=报错
`[levels]
none_level      = 121
sr_alm_level    = 122
intrm_alm_level = 123
pri_alm_level   = 124
sr_note_level   = 125
pri_note_level  = 126
sr_dbg_level    = 127
pri_dbg_level   = 128
[formats]
warn_format   = "[Date] %d [Pid] %p%n[Text] %m%n"
notice_format = "[Date] %d [Pid] %p%n[Text] %m%n"
debug_format  = "[Date] %d [Pid] %p%n[File] %F [Line] %L%n[Text] %m%n"
[rules]
my_cat.sr_alm_level = /home/zlog/TestZlog/zlog/nandflashlog/zlog.log; warn_format`
报错：
root@sunny:/home/zlog/TestZlog/zlog# zlog-chk-conf test_hello.conf 
11-30 14:50:45 ERROR (5434:rule.c:883) the 1st char[=] of file_path[= /home/zlog/TestZlog/zlog/nandflashlog/zlog.log] is wrong
11-30 14:50:45 ERROR (5434:conf.c:481) zlog_rule_new fail [my_cat.sr_alm_level = /home/zlog/TestZlog/zlog/nandflashlog/zlog.log; warn_format]
11-30 14:50:45 ERROR (5434:conf.c:309) parse configure file[test_hello.conf]line_no[15] fail
11-30 14:50:45 ERROR (5434:conf.c:310) line[my_cat.sr_alm_level = /home/zlog/TestZlog/zlog/nandflashlog/zlog.log; warn_format]

**Comment by HardySimpson** [comment]
my_cat.=sr_alm_level

具体可以看文档

**Comment by IotCoder-LangZhe** [comment]
这下成功谢谢。

**Comment by IotCoder-LangZhe** [comment]
`[rules]
my_cat.=sr_alm_level    "/home/zlog/TestZlog/zlog/nandflashlog/zlog.log"; warn_format
my_cat.=intrm_alm_level "/home/zlog/TestZlog/zlog/nandflashlog/zlog.log"; warn_format
my_cat.=pri_alm_level   "/home/zlog/TestZlog/zlog/nandflashlog/zlog.log"; warn_format
my_cat.=sr_note_level   "/home/zlog/TestZlog/zlog/nandflashlog/zlog.log"; notice_format
my_cat.=pri_note_level  "/home/zlog/TestZlog/zlog/nandflashlog/zlog.log"; notice_format
my_cat.=sr_dbg_level    "/home/zlog/TestZlog/zlog/emmclog/zlog.log";      debug_format
my_cat.=pri_dbg_level   "/home/zlog/TestZlog/zlog/emmclog/zlog.log";      debug_format`
您好，请问：
1.配置文件可以设定自定义变量吗，比如我相关把“/home/zlog/TestZlog/zlog/”设置成变量便于后期修改 还有%[]如果具体使用？
2.文件名称可以由程序输入吗，必须在配置里面写死？我有多个进程要求每个进程写一个日志文件。
3.还有日志按照时间归档后，库提供定期删除过期的日志的功能吗？

**Comment by HardySimpson** [comment]
详见文档  http://hardysimpson.github.io/zlog/UsersGuide-CN.html
