### ISSUE TITLE
zlog多线程释放资源

### ISSUE THREAD

**Issue by applecandyfromsky** [HardySimpson/zlog#117]
我的tcp服务器每次接到一个连接就建立一个线程，主线程永不退出。
在主线程里调用dzlog_init，子线程只用dzlog，如果子线程退出时调用zlog_fini，别的线程写log时好像会出错？
所以想问下zlog占用的内存会随线程数的增加而增加吗？
如果子线程不调用zlog_fini的话是不是就没办法释放资源了？

**Comment by lisongmin** [comment]
zlog完全是由你来控制的，这个就和申请内存一样，遵循在哪申请，在哪释放的原则，
在子线程里释放会导致多次释放的问题，不要在子线程里释放。

对于多线程，zlog只是通过锁来保证写入的一致性，并不会涉及资源的申请。

**Comment by applecandyfromsky** [comment]
好的，谢谢解答
