### ISSUE TITLE
warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"

### ISSUE THREAD

**Issue by matwei** [HardySimpson/zlog#119]
I've got the following error, when compiling under Fedora 23

    In file included from /usr/include/string.h:25:0,
                     from category.c:9:
    /usr/include/features.h:148:3: error: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated,  use _DEFAULT_SOURCE" [-Werror=cpp]
     # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
       ^
    cc1: all warnings being treated as errors

I had to compile it like this:

    CFLAGS=-D_DEFAULT_SOURCE make

That way I could compile it.

**Comment by jinankjain** [comment]
`src/fmacros.h` needs to updated from `#define _BSD_SOURCE` to `#define DEFAULT_SOURCE`

**Comment by SteveLauC** [comment]
I just checked `src/fmacros.h` finding it was already updated, perhaps we can close this issue?

**Comment by matwei** [comment]
Go ahead.
While I don't have Fedora 23, I just tested compiling zlog-1.2.15 on Ubuntu 20.04 and it worked fine.

**Comment by SteveLauC** [comment]
@matwei Then you can close it yourself, this is your issue:)
 I am not a maintainer or someone like that so I don't have the right to do that.
