### ISSUE TITLE
zlog配置按天分割日志，可否同时限制当天日志的文件大小

### ISSUE THREAD

**Issue by zhoukuanxi** [HardySimpson/zlog#149]
zlog如何配置按天分割日志，同时限制当天生成的文件大小。 
也就是结合按天分割和按大小分割两种方式。

**Comment by bineyond** [comment]
可以的，类似这么处理
default.*    "%E(HOME)/opt/var/log/fiber", 100MB ~ "%E(HOME)/opt/var/log/fiber-%d(%Y%m%d).#2s"

**Comment by zhoukuanxi** [comment]
@bineyond  谢指导，下面配置方法可实现, 问题已解决。
[rules]
*.*   "/var/log/mycat/mycat.%d(%F).log", 1MB ~"/var/log/mycat/mycat.%d(%F).#2s.log";simple

生成示例：
-rw------- 1 root root 1.0M Jul 15 09:00 mycat.2019-07-15.00.log
-rw------- 1 root root 1.0M Jul 15 09:00 mycat.2019-07-15.01.log
-rw------- 1 root root 1.0M Jul 15 09:01 mycat.2019-07-15.02.log
-rw------- 1 root root 1.0M Jul 15 09:01 mycat.2019-07-15.03.log
-rw------- 1 root root 351K Jul 15 09:01 mycat.2019-07-15.log
-rw------- 1 root root 1.0M Jul 16 09:00 mycat.2019-07-16.00.log
-rw------- 1 root root 1.0M Jul 16 09:00 mycat.2019-07-16.01.log
-rw------- 1 root root 176K Jul 16 09:00 mycat.2019-07-16.log
-rw------- 1 root root 1.0M Jul 17 09:00 mycat.2019-07-17.00.log
-rw------- 1 root root 1.0M Jul 17 09:00 mycat.2019-07-17.01.log
-rw------- 1 root root 176K Jul 17 09:00 mycat.2019-07-17.log
