### ISSUE TITLE
New log level called TRACE  lower than DEBUG

### ISSUE THREAD

**Issue by saynb** [HardySimpson/zlog#207]
We want to add another log level lower than DEBUG called TRACE. Most logging infrastructure follow this convention including log4j

https://www.tutorialspoint.com/log4j/log4j_logging_levels.htm

But zlog only follows

```
typedef enum {
	ZLOG_LEVEL_DEBUG = 20,
	ZLOG_LEVEL_INFO = 40,
	ZLOG_LEVEL_NOTICE = 60,
	ZLOG_LEVEL_WARN = 80,
	ZLOG_LEVEL_ERROR = 100,
	ZLOG_LEVEL_FATAL = 120
} zlog_level; 
```

**Comment by deemar** [comment]
log4j has 6 levels, and we have 6 too. I think you can make ZLOG_LEVEL_DEBUG to TRACE and ZLOG_LEVEL_INFO to DEBUG.

**Comment by saynb** [comment]
Agreed that log4j has only 6 levels. Do you see any harm with adding another log level? We want to be able to use it to add tracing capabilities to our software. It could potentially be a step towards getting the naming convention right here eventually.

**Comment by deemar** [comment]
I think it is useless to add another level but if you insist you can just PR.
