### ISSUE TITLE
auto tool 的repo中，MacOSX 上无法通过编译，因为`pthread_threadid_np`不可见

### ISSUE THREAD

**Issue by zhentao-huang** [HardySimpson/zlog#226]
这个问题，在这个repo中[修了](https://github.com/HardySimpson/zlog/commit/cd40f93b2c080d112284a2fbf7b3cc783724f521)
，但是[auto tool 工程](https://github.com/bmanojlovic/zlog) 中没有。

cd40 这个提交只修改了makefile，没有动代码。方法通过在make file中追加一个宏 _DARWIN_C_SOURCE
我在auto tool的repo 提了PR，采用了同样的方法，改了build文件。

而auto tool 的 owner认为他只管同步代码，所以没有采纳这个[PR](https://github.com/bmanojlovic/zlog/pull/3)。

不管怎样，这个问题在 auto tool的fork依然存在。希望有人帮忙解决。

**Comment by deemar** [comment]
你可以把PR提到这个仓里面来

**Comment by zhentao-huang** [comment]
我只改了`configure.ac`, `src/Makefile.am` 这两个文件，都不是本地repo有的。

要么我得修改`src/fmacros.h，可以的话我就做这个提交
