### ISSUE TITLE
Is this library multiprocess safe?

### ISSUE THREAD

**Issue by kevin-tso** [HardySimpson/zlog#235]

**Comment by deemar** [comment]
No

**Comment by kevin-tso** [comment]
Is there a solution?

**Comment by deemar** [comment]
What is your context?

**Comment by kevin-tso** [comment]
Multiple processes securely write to the same log file

**Comment by kevin-tso** [comment]
Hope it can be cross-platform

**Comment by deemar** [comment]
> Multiple processes securely write to the same log file

I will not suggest anyone to do that, with or without this lib

**Comment by kevin-tso** [comment]
OK Wanted to replace syslog, but portable across platforms
