### ISSUE TITLE
配置规则没有生效

### ISSUE THREAD

**Issue by zhuilang** [HardySimpson/zlog#237]
从 b8d9634a1a9fb6c60ec2a23b0cb4b5e29e6e3502 这次提交开始，配置没有生效导致单个日志文件越来越大

**Comment by jxpenglin** [comment]
是的 配置的文件大小没有生效：  
`*.*          "./log/aa.log", 10MB ~ "./log/aa-%d(%Y%m%d).#2s.log";simple`
