### ISSUE TITLE
多线程环境，fork后的子进程中，如果继续使用log记录日志，有几率出现死锁

### ISSUE THREAD

**Issue by lisongmin** [HardySimpson/zlog#62]
pid = fork()
if (pid == 0)
{
    log_info("test."); // 这里可能会造成死锁
}

执行fork的时候，如果有别的线程已经加了写锁，fork后的子进程也会处于写锁的状态，
这个时候，子进程再写日志，会出现死锁。

现在规避的方案是fork后，子进程不要调用log记录日志，不知道是否还有更好的方法

**Comment by kevin-tso** [comment]
多进程写同一日志文件支持吗

**Comment by kevin-tso** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
