### ISSUE TITLE
zlog一直不释放内存

### ISSUE THREAD

**Issue by fashionwu** [HardySimpson/zlog#67]
在服务器上用zlog，程序要到退出的时候才调用zlog_fini()，所以，程序不退出时，内存一直不会释放，服务器占的内存越来越大，这个问题怎么解决呢？按理说，这个需求应该做服务器的都有，是不是我哪里用错了呢？
后来发现zlog_init原来可以调用多次，我到一定的时候zlog_fini，释放内存，然后再zlog_reload，就解决了内存一直不释放的问题，但是这样又会出现另外的问题：当zlog_fini、 zlog_init 、 zlog_reload和dzlog的函数在不同的线程的情况下，在打日志的时候会崩溃，原因是zlog_default_category为空。即在zlog_fini、 zlog_init之间的那段时间打日志会崩溃，改怎么解决呢？

**Comment by KeJiAndHu** [comment]
> 你是否一直在增加问题？

如果一直增加线程呢，我现在遇到了类似问题
