### ISSUE TITLE
zlog版本1.2.12.1根据zlog使用手册5.6节的知道，发现无法实现文件转档功能。

### ISSUE THREAD

**Issue by openfree01** [HardySimpson/zlog#71]
zlog版本1.2.12.1根据zlog使用手册5.6节的知道，发现无法实现文件转档功能。

**Comment by HardySimpson** [comment]
能具体贴一下配置和没有转档的行为吗？

**Comment by HardySimpson** [comment]
非常感谢您的回复~
配置文件见附件test_init.conf,测试代码见附件zlog_test.c‍‍
测试主机环境：
编译命令：
gcc -g -o zlog_test zlog_test.c -lzlog -lpthread‍
测试方式：./zlog_test 10 1000000‍
日志显示：


你用的配置文件，test.conf里面没有配置转档，具体配置方式详见：
http://hardysimpson.github.io/zlog/UsersGuide-CN.html#htoc26
‍
并没有转档。

非常感谢解答~

**Comment by HardySimpson** [comment]
我重现了这个bug，根据你的配置

    [global]
    strict init = true
    reload conf period = 0
    
    buffer min = 1KB
    buffer max = 4KB
    
    #rotate lock file = /tmp/zlog.lock
    rotate lock file = self
    default format = "%d %V [%p:%f:%L] %m%n"
    
    file perms = 755 
    fsync period = 0
    
    [formats]
    simple = "%m%n"
    
    [rules]
    gvfs.=DEBUG    "/tmp/gvfs_debug.log"
    gvfs.=INFO     "/tmp/gvfs_info.log", 10MB ~ "/gvfs_info-%d(%Y%m%d).#2s.log" 
    gvfs.=NOTICE   "/tmp/gvfs_notice.log"
    gvfs.=WARN     "/tmp/gvfs_warn.log"
    gvfs.=ERROR    "/tmp/gvfs_error.log"
    gvfs.=FATAL    "/tmp/gvfs_fatal.log"

我把zlog本身的debug打开
    ZLOG_PROFILE_DEBUG=/tmp/zlog.debug.log
    ZLOG_PROFILE_ERROR=/tmp/zlog.error.log

最后在/tmp/zlog.error.log里面看到

01-09 18:00:31 ERROR (10961:rotater.c:277) rename[/tmp/gvfs_info.log]->[gvfs_info-20150109.00.log] fail, errno[18] 

当然我也看到过 18的errno，文档不在同一个分区上做rename会失败。不知道你属于那种，不过我估计修改你的配置为：

    gvfs.=INFO     "/tmp/gvfs_info.log", 10MB ~ "/var/zlog/gvfs_info-%d(%Y%m%d).#2s.log" 

会解决这个问题。

**Comment by openfree01** [comment]
经过多次验证，应该是新版本代码中存在bug，而不是配置引起的问题~

**Comment by lengyuyan** [comment]
当然我也看到过 18的errno，文档不在同一个分区上做rename会失败  ----我属于这种，这种有解决方案吗

**Comment by zhouyunbin** [comment]
您好，已收到您的来信
