### ISSUE TITLE
已经验证测试zlog-1.2.12.1存在bug，请各位谨慎

### ISSUE THREAD

**Issue by openfree01** [HardySimpson/zlog#72]
同样的配置文件，同样的测试代码，使用zlog-1.2.12.1不会转档，但使用zlog-1.2.11版本是正常的，那么可以确定新版本改出了bug。

**Comment by HardySimpson** [comment]
看到了，前两天忙没能回复。
zlog-1.2.12.1 这个tag是哪里加的？我的库里面没有这个版本啊，只有1.2.12这个tag
现在看来可能的确是代码出了问题，但出问题的是你手上的那份，重新下载1.2.12试试看

**Comment by HardySimpson** [comment]
已和楼主联系过是代码版本问题，结束～～
