### ISSUE TITLE
make doc fails due to xelatex error "kpathsea:make_tex: Invalid fontname `SimSun:', contains ':'"

### ISSUE THREAD

**Issue by krichter722** [HardySimpson/zlog#73]
invoking `make doc` after installation of `lyx` and `hevea` and `./configure && make` fails with 

	$ make doc
	Entering auto-apt mode: make doc
	Exit the command to leave auto-apt mode.
	cd doc && make
	make[1]: Entering directory '/mnt/DATA/sources/zlog/doc'
	lyx -f -e pdf2 UsersGuide-EN.lyx
	lyx -f -e pdf4 UsersGuide-CN.lyx
	lyx -f -e pdflatex UsersGuide-EN.lyx
	lyx -f -e pdflatex UsersGuide-CN.lyx

	Running: xelatex  "UsersGuide-CN.tex" > /dev/null
	hevea book.hva -s UsersGuide-EN.tex
	hevea book.hva -s UsersGuide-CN.tex

	Running: pdflatex  "UsersGuide-EN.tex" > /dev/null
	This is XeTeX, Version 3.14159265-2.6-0.99991 (TeX Live 2014/Debian) (preloaded format=xelatex)
	 restricted \write18 enabled.
	This is pdfTeX, Version 3.14159265-2.6-1.40.15 (TeX Live 2014/Debian) (preloaded format=pdflatex)
	 restricted \write18 enabled.
	entering extended mode
	(./UsersGuide-EN.tex
	LaTeX2e <2014/05/01>
	Babel <3.9k> and hyphenation patterns for 79 languages loaded.

	entering extended mode
	(./UsersGuide-CN.tex
	LaTeX2e <2014/05/01>
	Babel <3.9k> and hyphenation patterns for 79 languages loaded.

	Running: pdflatex  "UsersGuide-EN.tex" > /dev/null
	This is pdfTeX, Version 3.14159265-2.6-1.40.15 (TeX Live 2014/Debian) (preloaded format=pdflatex)
	 restricted \write18 enabled.
	entering extended mode
	(./UsersGuide-EN.tex
	LaTeX2e <2014/05/01>
	Babel <3.9k> and hyphenation patterns for 79 languages loaded.

	Running: pdflatex  "UsersGuide-EN.tex" > /dev/null
	This is pdfTeX, Version 3.14159265-2.6-1.40.15 (TeX Live 2014/Debian) (preloaded format=pdflatex)
	 restricted \write18 enabled.
	entering extended mode
	(./UsersGuide-EN.tex
	LaTeX2e <2014/05/01>
	Babel <3.9k> and hyphenation patterns for 79 languages loaded.

	hevea book.hva -s UsersGuide-EN.tex
	hevea book.hva -s UsersGuide-CN.tex
	kpathsea:make_tex: Invalid fontname `SimSun:', contains ':'
	kpathsea:make_tex: Invalid fontname `SimSun:', contains ':'
	kpathsea:make_tex: Invalid fontname `SimSun:', contains ':'
	kpathsea:make_tex: Invalid fontname `SimSun:', contains ':'
	kpathsea:make_tex: Invalid fontname `SimSun:', contains ':'
	kpathsea:make_tex: Invalid fontname `SimSun:', contains ':'
	kpathsea:make_tex: Invalid fontname `SimSun:', contains ':'
	kpathsea:make_tex: Invalid fontname `SimSun:', contains ':'
	kpathsea:make_tex: Invalid fontname `SimSun:', contains ':'
	kpathsea:make_tex: Invalid fontname `SimSun:', contains ':'
	kpathsea:make_tex: Invalid fontname `SimSun:', contains ':'
	kpathsea:make_tex: Invalid fontname `SimSun:', contains ':'
	support/Systemcall.cpp (273): Systemcall: 'xelatex  "UsersGuide-CN.tex"' finished with exit code 1
	makefile:17: recipe for target 'UsersGuide-CN.pdf' failed
	make[1]: *** [UsersGuide-CN.pdf] Error 1
	make[1]: Leaving directory '/mnt/DATA/sources/zlog/doc'
	makefile:15: recipe for target 'doc' failed
	make: *** [doc] Error 2

with ca6162be1608839e99c6388c28488c51ccf98e4a on Ubuntu 14.10 amd64.

**Comment by HardySimpson** [comment]
thanks k, I've consider of change the doc all to .md, leave the latex land....
