### ISSUE TITLE
实现多线程安全一共使用了多少把锁？

### ISSUE THREAD

**Issue by RuyiDu** [HardySimpson/zlog#81]
我想知道zlog为了实现多线程安全一共使用了多少把锁？

**Comment by HardySimpson** [comment]
大的锁只有一把，是用来读取配置信息用的，读写锁，效率很高。
其他的，在转档时需要获取一把锁。但这并不是每次写日志的时候都会去获取。

**Comment by RuyiDu** [comment]
好的，使用锁是一种昂贵的代价，对性能消耗很严重，最好是少用甚至不用。
