### ISSUE TITLE
Categories as variables

### ISSUE THREAD

**Issue by blakemcbride** [HardySimpson/zlog#91]
I am looking for a good logging facility for C.  I am new to zlog.  I see that one creates a new category by defining a variable and initializing it to represent a new category.  I definitely understand the necessity for categories, but I can't understand why they were implemented the way they were.  Every time you create a category, you have to create a new variable and pass it around to all of the functions that are in that category - or, worse yet, create a global variable.  This is crazy.  To implement zlog, I'd have to make massive amounts of changes to my source code to accommodate the passing of category variables.  It seems like string category names would make a lot more sense.  There would be no need to pass those variables all over the place.  Perhaps a hash table could associate a string name to a category object kept internally to zlog.  zlog is very intrusive.  Or, am I missing something?

Thanks.

Blake McBride

**Comment by DigiTester** [comment]
I find it generally useful to put a wrapper around any logging tool. Partly that makes it easy to customise, and partly easy to change (I had to change from log4cpp to zlog when I couldn't get it to build on some new hardware we got, for example. Only ~30k log calls in the two projects, but changing them manually would have been somewhat tedious).

At the most basic level I just have:
#define LOG_TRACE(...) dzlog_trace(__VA_ARGS__)

But for category logging I prefer to put the category in the macro name (and TRACE is my 'even less important' custom logging level):
#define LOG_CONFIG_TRACEMSG(msg) zlog(zlog_cat_config__, __FILE__, sizeof(__FILE__)-1, __func__, sizeof(__func__)-1, __LINE__, LOG_LEVEL_TRACE, msg)

Except that in one particular case I needed the log output to go one of two ways depending on details, so I ended up with this pass-the-category version as well:
#define LOG_TRACE_CATEGORY(cat,args...) zlog(cat, __FILE__, sizeof(__FILE__)-1, __func__, sizeof(__func__)-1, __LINE__, LOG_LEVEL_TRACE, args)

This also helps me solve the problem that gcc and cppcheck can't deal with the amount of macro nesting going on, so often miss errors that they would pick up if I was using printf... like this:

#if defined TEST_LOGGING
#define LOG_TRACE(fmt, args...) printf(fmt "\n", args)
#define LOG_TRACEMSG(msg) printf(msg "\n")

(defining that also means I can send all output to the terminal, of for some reason I wanted to do that).

I suspect but have not bothered finding out, that you could simply pass the category string value into a macro or log call:

// UNTESTED!!!!
#define LOG_CONFIG_TRACEMSG(msg) zlog(zlog_get_category("foo"), __FILE__, sizeof(__FILE__)-1, __func__, sizeof(__func__)-1, __LINE__, LOG_LEVEL_TRACE, msg)
#define LOG_TRACE(cat,msg) zlog(zlog_get_category(cat), __FILE__, sizeof(__FILE__)-1, __func__, sizeof(__func__)-1, __LINE__, LOG_LEVEL_TRACE, msg)


HTH
